@startuml
hide footbox

hide footbox

actor "User A"

"User A" -> "App Server": Sent a POST request (with JWT) \nto add new friend
"App Server" -> "Redis Server": Check JWT BlackList
"App Server" -> "Redis Server": Validate JWT then add new friend list
"App Server" -> "User A": Return result to user A

@enduml