@startuml
hide footbox

actor "User A"
actor "User B"

note over "User A": User A was handshaked and subscribed
"User A" -> "App Server": Send a message to user B
"App Server" --> "User B": Send message to topic <user id B> \nwhich user B was subscribed
"App Server" -> "Redis Server": Store this message to redis

@enduml